"use client";

import { useEffect } from "react";
import { SiteHeader } from "./_components/SiteHeader";
import { SiteFooter } from "./_components/InnerShell";
import { ExperienceVisual } from "./_components/ExperienceVisual";
import { selectText, useLanguage, type LocalizedText } from "./_components/LanguageProvider";

const assetBase = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

const clients = [
  { name: "Barrick", file: "barrick.png" }, { name: "Glencore", file: "glencore.png" },
  { name: "Veladero", file: "veladero.png" }, { name: "Mansfield Minera", file: "mansfield.png" },
  { name: "LDC", file: "ldc.png" }, { name: "Bunge", file: "bunge.png" },
  { name: "Molinos Agro", file: "molinos.png" }, { name: "ADM", file: "adm.png" },
  { name: "Puerto Las Losas", file: "pll.png" }, { name: "Puerto Ventanas", file: "pvsa.png" },
  { name: "YPF", file: "ypf.png" },
];

const sectors: { n: string; title: LocalizedText; copy: LocalizedText }[] = [
  { n: "01", title: { es: "Años de Experiencia", en: "Years of Experience" }, copy: { es: "Desarrollando sistemas de manejo de materiales a granel desde 2001.", en: "Developing bulk material handling systems since 2001." } },
  { n: "02", title: { es: "Ingeniería Mecánica Especializada", en: "Mechanical Engineering Excellence" }, copy: { es: "Ingeniería especializada en manejo de materiales a granel, abarcando ingeniería conceptual, básica y de detalle, integrada con fabricación y ejecución de proyectos.", en: "Specialized engineering in bulk material handling, covering conceptual, basic and detailed design, integrated with project execution and manufacturing." } },
  { n: "03", title: { es: "Ejecución integral", en: "End-to-end execution" }, copy: { es: "Desde los estudios de factibilidad hasta la puesta en marcha.", en: "From feasibility studies through commissioning." } },
  { n: "04", title: { es: "Proyectos ejecutados", en: "Projects delivered" }, copy: { es: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", en: "Lorem ipsum dolor sit amet, consectetur adipiscing elit." } },
];

const services: { n: string; slug: string; title: LocalizedText; copy: LocalizedText }[] = [
  { n: "01", slug: "bulk-material-handling-equipment", title: { es: "Equipos para manejo de materiales a granel", en: "Bulk material handling equipment" }, copy: { es: "Diseñamos y suministramos transportadores de banda, pipe conveyors, transportadores cerrados, shuttle y reversibles, overland conveyors, alimentadores, elevadores, tripper cars y sistemas móviles o fijos de transferencia.", en: "We design and supply belt, pipe, enclosed, shuttle, reversible and overland conveyors, along with belt feeders, bucket elevators, tripper cars and mobile or fixed transfer systems." } },
  { n: "02", slug: "conveyor-components", title: { es: "Componentes para transportadores", en: "Conveyor components" }, copy: { es: "Proveemos estructuras, galerías, torres de transferencia, chutes, tolvas, poleas, soporte de rodillos, sistemas de contrapeso, limpieza de banda, cubiertas y accesorios mecánicos.", en: "We supply structures, galleries, transfer towers, chutes, hoppers, pulleys, idler stations, take-up systems, belt cleaning systems, covers and mechanical accessories." } },
  { n: "03", slug: "port-and-mining-systems", title: { es: "Sistemas portuarios y mineros", en: "Port and mining systems" }, copy: { es: "Desarrollamos sistemas de acopio, recepción y transferencia para concentrado de cobre, carbón, granos, litio y otros materiales mineros e industriales.", en: "We develop storage, receiving and transfer systems for copper concentrate, coal, grain, lithium and other mining and industrial materials." } },
  { n: "04", slug: "engineering-and-project-services", title: { es: "Servicios de ingeniería y proyectos", en: "Engineering and project services" }, copy: { es: "Brindamos ingeniería conceptual, básica y de detalle, diseño mecánico, soporte de compras, fabricación, control de calidad, instalación, puesta en marcha, mantenimiento y soporte técnico.", en: "We provide conceptual, basic and detailed engineering, mechanical design, procurement support, manufacturing, quality control, installation, commissioning, maintenance and technical support." } },
];

const copy = {
  es: {
    heroLine: "From concept to", heroAccent: "commissioning.", heroAlt: "Sistema KRK para transporte de materiales a granel", heroDescription: "Ingeniería, fabricación y ejecución de sistemas para transporte de materiales a granel en minería, puertos, agroindustria, energía e industria.", products: "Productos y servicios", discover: "Descubrir KRK",
    trusted: "EMPRESAS QUE CONFÍAN EN KRK", clients: "CLIENTES & PROYECTOS", trustedAria: "Empresas que confían en KRK",
    about: "QUIÉNES SOMOS", since: "Desde 2001 desarrollando sistemas de manejo de materiales a granel.", aboutTitle: "Una empresa enfocada en", aboutAccent: "ingeniería y movimiento", aboutEnd: "de materiales.", aboutP1: "KRK Latinoamericana S.A. es una empresa de capitales argentinos especializada en ingeniería, fabricación y ejecución de proyectos para el manejo de materiales a granel.", aboutP2: "Desde 2001 participamos en proyectos de distinta escala y complejidad, integrando estudios de factibilidad, ingeniería conceptual, diseño de detalle, fabricación, suministro, montaje y puesta en marcha. Nuestra experiencia, capacidad técnica y red de fabricación nos permite acompañar a cada cliente con soluciones confiables, competitivas y adaptadas a las exigencias de su operación.", company: "Conocer la empresa", solutions: "Ver soluciones",
    statYears: "Años de experiencia", statLifecycle: "Ejecución integral", statProjects: "Proyectos ejecutados",
    expertise: "ÁREAS DE EXPERIENCIA", movement: "ENGINEERING MOVEMENT", integrated: "Ingeniería integral para", demanding: "proyectos exigentes.", viewProducts: "Ver productos y servicios", talk: "Hablar con ingeniería",
    ourServices: "NUESTROS PRODUCTOS Y SERVICIOS", serviceTitle: "Soluciones integrales para el manejo de", bulk: "materiales a granel.", serviceIntro: "Equipos, componentes e ingeniería para sistemas de transporte y manejo de materiales a granel en operaciones industriales, mineras y portuarias.", advice: "Solicitar asesoramiento", capabilities: "Ver capacidades", viewService: "Ver servicio",
    bannerAlt: "Ingeniería y fabricación de KRK", bannerCopy: "KRK integra todas las etapas del proyecto en una misma solución: análisis técnico, ingeniería, fabricación, suministro, montaje y puesta en marcha. Esta visión permite reducir interfaces, ordenar la ejecución y asegurar sistemas confiables para operaciones de largo plazo.", discuss: "Conversemos sobre su proyecto", process: "Conocer el proceso",
    projectAlt: "Sistema transportador de KRK en operación", field: "CAPACIDAD EN CAMPO / 01", fromConcept: "FROM CONCEPT TO COMMISSIONING", oneSolution: "Una solución.", everyStage: "Todas las etapas.", projectCopy: "Nuestra experiencia, capacidad técnica y red de fabricación nos permite acompañar a cada cliente con soluciones confiables, competitivas y adaptadas a las exigencias de su operación.", mining: "Minería", agribusiness: "Agroindustria", energy: "Energía e industria", ports: "Puertos y terminales", start: "Iniciar una conversación", viewServices: "Ver servicios",
    contact: "CONTÁCTANOS", contactTitle: "Movemos lo que", contactAccent: "importa.", contactCopy: "Contanos brevemente sobre tu operación o proyecto. Nuestro equipo técnico se pondrá en contacto con vos.", conversation: "INICIAR UNA CONVERSACIÓN", name: "Nombre y apellido", namePlaceholder: "Tu nombre", companyLabel: "Empresa", companyPlaceholder: "Nombre de la empresa", email: "Email", emailPlaceholder: "nombre@empresa.com", phone: "Teléfono", help: "¿Cómo podemos ayudarte?", helpPlaceholder: "Proyecto, operación o necesidad técnica", send: "Enviar consulta", back: "Volver al inicio",
  },
  en: {
    heroLine: "From concept to", heroAccent: "commissioning.", heroAlt: "KRK bulk material handling system", heroDescription: "Engineering, manufacturing and execution of bulk material handling systems for mining, ports, agribusiness, energy and industrial operations.", products: "Products and services", discover: "Discover KRK",
    trusted: "COMPANIES THAT TRUST KRK", clients: "CLIENTS & PROJECTS", trustedAria: "Companies that trust KRK",
    about: "ABOUT US", since: "Developing bulk material handling systems since 2001.", aboutTitle: "A company focused on", aboutAccent: "engineering and movement", aboutEnd: "of materials.", aboutP1: "KRK Latinoamericana S.A. is an Argentine-owned company specializing in engineering, manufacturing and project execution for bulk material handling.", aboutP2: "Since 2001, we have participated in projects of varying scale and complexity, integrating feasibility studies, conceptual engineering, detailed design, manufacturing, supply, assembly and commissioning. Our experience, technical capabilities and manufacturing network allow us to support every client with reliable, competitive solutions tailored to their operating requirements.", company: "Learn about the company", solutions: "View solutions",
    statYears: "Years of experience", statLifecycle: "Project Lifecycle", statProjects: "Projects delivered",
    expertise: "AREAS OF EXPERTISE", movement: "ENGINEERING MOVEMENT", integrated: "Integrated engineering for", demanding: "demanding projects.", viewProducts: "View products and services", talk: "Talk to engineering",
    ourServices: "OUR PRODUCTS AND SERVICES", serviceTitle: "Integrated solutions for", bulk: "bulk material handling.", serviceIntro: "Equipment, components and engineering for bulk material conveying and handling systems across industrial, mining and port operations.", advice: "Request guidance", capabilities: "View capabilities", viewService: "View service",
    bannerAlt: "KRK engineering and manufacturing", bannerCopy: "KRK integrates every project stage into a single solution: technical analysis, engineering, manufacturing, supply, assembly and commissioning. This approach reduces interfaces, streamlines execution and ensures reliable systems for long-term operations.", discuss: "Let's discuss your project", process: "Explore the process",
    projectAlt: "KRK conveyor system in operation", field: "FIELD CAPABILITY / 01", fromConcept: "FROM CONCEPT TO COMMISSIONING", oneSolution: "One solution.", everyStage: "Every stage.", projectCopy: "Our experience, technical capabilities and manufacturing network allow us to support every client with reliable, competitive solutions tailored to their operating requirements.", mining: "Mining", agribusiness: "Agribusiness", energy: "Energy and industry", ports: "Ports and terminals", start: "Start a conversation", viewServices: "View services",
    contact: "CONTACT US", contactTitle: "We move what", contactAccent: "matters.", contactCopy: "Tell us briefly about your operation or project. Our technical team will get in touch with you.", conversation: "START A CONVERSATION", name: "Full name", namePlaceholder: "Your name", companyLabel: "Company", companyPlaceholder: "Company name", email: "Email", emailPlaceholder: "name@company.com", phone: "Phone", help: "How can we help?", helpPlaceholder: "Project, operation or technical requirement", send: "Send enquiry", back: "Back to top",
  },
} as const;

function DoubleActions({ primary, secondary, primaryHref = "#contacto", secondaryHref = "#soluciones", light = false }: { primary: string; secondary: string; primaryHref?: string; secondaryHref?: string; light?: boolean }) {
  return <div className={`double-actions ${light ? "double-actions-light" : ""}`}><a className="action-main" href={primaryHref}><span>{primary}</span><i>↗</i></a><a className="action-alt" href={secondaryHref}><i>↓</i><span>{secondary}</span></a></div>;
}

export default function Home() {
  const { language } = useLanguage();
  const text = copy[language];

  useEffect(() => {
    const items = document.querySelectorAll<HTMLElement>("[data-reveal]");
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add("in-view")), { threshold: 0.14 });
    items.forEach((item) => observer.observe(item));
    return () => observer.disconnect();
  }, []);

  return <main>
    <SiteHeader />
    <section className="hero" id="top"><img className="hero-image" src={`${assetBase}/images/hero-portada-krk.webp`} alt={text.heroAlt} /><div className="hero-shade" /><div className="hero-grid" /><div className="hero-content container"><div className="hero-kicker"><span>MOVING WHAT MATTERS</span></div><h1><span className="hero-line">{text.heroLine}</span><span className="hero-line hero-accent">{text.heroAccent}</span></h1><p className="hero-description">{text.heroDescription}</p><DoubleActions primary={text.products} secondary={text.discover} primaryHref={`${assetBase}/servicios/`} secondaryHref={`${assetBase}/quienes-somos/`} light /></div><div className="hero-tech hero-tech-a"><span>01</span><i /></div><div className="hero-tech hero-tech-b"><span>2001 — 2026</span><i /></div></section>

    <section className="trust" id="experiencia"><div className="container trust-head"><span>{text.trusted}</span><span>{text.clients}</span></div><div className="logo-marquee" aria-label={text.trustedAria}><div className="logo-track">{[...clients, ...clients].map((client, index) => <div className="client-logo" key={`${client.name}-${index}`}><img src={`${assetBase}/logos/${client.file}`} alt={client.name} /></div>)}</div></div></section>

    <section className="intro section" id="empresa" data-reveal><div className="container intro-grid"><div><div className="eyebrow"><span /> {text.about}</div><p className="side-note">{text.since}</p></div><div><h2>{text.aboutTitle}<br /><em>{text.aboutAccent}</em><br />{text.aboutEnd}</h2><div className="intro-copy"><p>{text.aboutP1}</p><p>{text.aboutP2}</p></div><DoubleActions primary={text.company} secondary={text.solutions} primaryHref={`${assetBase}/quienes-somos/`} secondaryHref={`${assetBase}/servicios/`} /></div></div><div className="container stats"><div><strong><sup>+</sup>25</strong><span>{text.statYears}</span></div><div><strong><sup>+</sup>360</strong><span>{text.statLifecycle}</span></div><div><strong><sup>+</sup>700</strong><span>{text.statProjects}</span></div></div></section>

    <section className="sectors section" id="sectores" data-reveal><div className="sectors-glow sectors-glow-a" /><div className="sectors-glow sectors-glow-b" /><div className="container"><div className="section-title-row"><div className="eyebrow light"><span /> {text.expertise}</div><div><p className="section-overline">{text.movement}</p><h2>{text.integrated}<br /><em>{text.demanding}</em></h2></div></div><div className="sector-grid">{sectors.map((sector) => <article className="sector-card" key={sector.n}><div className="card-grid" /><div className="card-top"><span>KRK / {sector.n}</span><b>↗</b></div><ExperienceVisual type={sector.n} /><div className="sector-copy sector-copy-factual"><h3>{selectText(sector.title, language)}</h3><p>{selectText(sector.copy, language)}</p></div></article>)}</div><DoubleActions primary={text.viewProducts} secondary={text.talk} primaryHref={`${assetBase}/servicios/`} secondaryHref="#contacto" light /></div></section>

    <section className="services section" id="soluciones" data-reveal><div className="container services-grid"><div className="services-intro"><div className="eyebrow"><span /> {text.ourServices}</div><h2>{text.serviceTitle} <em>{text.bulk}</em></h2><p>{text.serviceIntro}</p><DoubleActions primary={text.advice} secondary={text.capabilities} primaryHref="#contacto" secondaryHref={`${assetBase}/servicios/`} /></div><div className="service-list">{services.map((service) => <a className="service-entry" href={`${assetBase}/servicios/${service.slug}/`} key={service.n}><span>{service.n}</span><div><h3>{selectText(service.title, language)}</h3><p>{selectText(service.copy, language)}</p><strong>{text.viewService} <i>↗</i></strong></div><b>↗</b></a>)}</div></div></section>

    <section className="engineering-banner" data-reveal><img src={`${assetBase}/images/BACK-002.jpg`} alt={text.bannerAlt} /><div className="banner-shade" /><div className="container banner-content"><div className="eyebrow light"><span /> {text.movement}</div><h2>{text.integrated}<br /><em>{text.demanding}</em></h2><p>{text.bannerCopy}</p><DoubleActions primary={text.discuss} secondary={text.process} primaryHref="#contacto" secondaryHref={`${assetBase}/servicios/engineering-and-project-services/`} light /></div></section>

    <section className="project section" data-reveal><div className="container project-grid"><div className="project-image"><img src={`${assetBase}/images/IMG-009.jpg`} alt={text.projectAlt} /><span>{text.field}</span></div><div className="project-copy"><div className="eyebrow"><span /> {text.fromConcept}</div><h2>{text.oneSolution}<br /><em>{text.everyStage}</em></h2><p>{text.projectCopy}</p><dl><div><dt>01</dt><dd>{text.mining}</dd></div><div><dt>02</dt><dd>{text.agribusiness}</dd></div><div><dt>03</dt><dd>{text.energy}</dd></div><div><dt>04</dt><dd>{text.ports}</dd></div></dl><DoubleActions primary={text.start} secondary={text.viewServices} primaryHref="#contacto" secondaryHref="#soluciones" /></div></div></section>

    <section className="contact" id="contacto" data-reveal><div className="contact-gridlines" /><div className="contact-glow contact-glow-a" /><div className="contact-glow contact-glow-b" /><div className="contact-beam" /><div className="container contact-grid"><div className="contact-heading"><div className="eyebrow light"><span /> {text.contact}</div><h2>{text.contactTitle}<br /><em>{text.contactAccent}</em></h2><p>{text.contactCopy}</p></div><div className="contact-side"><div className="form-head"><span>{text.conversation}</span><b>01 / 04</b></div><form className="contact-form" action="mailto:contactenos@krk.com" method="post" encType="text/plain"><label><span>{text.name}</span><input type="text" name="nombre" autoComplete="name" required placeholder={text.namePlaceholder} /></label><label><span>{text.companyLabel}</span><input type="text" name="empresa" autoComplete="organization" placeholder={text.companyPlaceholder} /></label><div className="form-row"><label><span>{text.email}</span><input type="email" name="email" autoComplete="email" required placeholder={text.emailPlaceholder} /></label><label><span>{text.phone}</span><input type="tel" name="telefono" autoComplete="tel" placeholder="+54" /></label></div><label><span>{text.help}</span><textarea name="mensaje" required rows={3} placeholder={text.helpPlaceholder} /></label><div className="form-actions"><button type="submit"><span>{text.send}</span><i>↗</i></button><a href="#top"><i>↓</i><span>{text.back}</span></a></div></form></div></div></section>
    <SiteFooter />
  </main>;
}
