import { ServiceDetail, type ProductItem } from "../../_components/ServiceDetail";

const items: ProductItem[] = [
  { title: "OVERLAND CONVEYORS", image: "PORTADA-006.jpg", en: "Long-distance conveying systems engineered to optimize energy efficiency, reduce operating costs and provide reliable bulk material transportation across challenging terrain.", es: "Sistemas de transporte de larga distancia diseñados para optimizar la eficiencia energética, reducir los costos operativos y garantizar un transporte confiable de materiales a granel sobre terrenos de alta complejidad." },
  { title: "ENCLOSED CONVEYORS", image: "BACK-002.jpg", en: "Fully enclosed conveyor systems designed to minimize dust emissions and environmental impact. External bearings and rotating components improve reliability, reduce maintenance and enhance operational safety, particularly in grain and soybean handling.", es: "Sistemas de transporte completamente cerrados diseñados para minimizar las emisiones de polvo y el impacto ambiental. Los rodamientos y componentes rotativos externos mejoran la confiabilidad, reducen el mantenimiento y aumentan la seguridad operativa, especialmente en el manejo de granos y soja." },
  { title: "BUCKET ELEVATORS", image: "IMG-009.jpg", en: "Bucket elevators engineered for reliable and continuous vertical transportation of bulk materials, combining high operational efficiency, low maintenance requirements and long service life.", es: "Elevadores de cangilones diseñados para el transporte vertical continuo y confiable de materiales a granel, combinando alta eficiencia operativa, bajos requerimientos de mantenimiento y una prolongada vida útil." },
  { title: "TRIPPER CARS", image: "PORTADA-003.jpg", en: "Engineered tripper cars providing accurate and flexible material distribution, maximizing storage capacity and improving the operational efficiency of stockpiles, silos and bulk material storage facilities.", es: "Diseñados para proporcionar una distribución precisa y flexible de materiales, maximizando la capacidad de almacenamiento y mejorando la eficiencia operativa de acopios, silos e instalaciones de almacenamiento de materiales a granel." },
  { title: "GRASSHOPPERS", image: "IMG-001.jpg", en: "Modular and portable conveyor systems designed to provide flexible bulk material transfer, allowing quick relocation and efficient adaptation to changing operational requirements.", es: "Sistemas transportadores modulares y portátiles diseñados para brindar una transferencia flexible de materiales a granel, permitiendo una rápida reubicación y una eficiente adaptación a los cambios operativos." },
  { title: "BELT FEEDERS", image: "img-002.jpg", en: "Engineered belt feeders designed to provide accurate and reliable bulk material extraction, ensuring precise flow control and consistent feeding to downstream equipment.", es: "Alimentadores de banda diseñados para proporcionar una extracción precisa y confiable de materiales a granel, garantizando un control exacto del flujo y una alimentación uniforme hacia los equipos posteriores del proceso." },
];

export default function Page() { return <ServiceDetail title="Bulk material handling equipment" image="PORTADA-006.jpg" en="Engineered conveying equipment for reliable, efficient and continuous bulk material handling across demanding industrial operations." es="Equipos de transporte diseñados para el manejo confiable, eficiente y continuo de materiales a granel en operaciones industriales exigentes." items={items} />; }
